Update CI-CD.yaml

diff --git a/.github/workflows/CI-CD.yaml b/.github/workflows/CI-CD.yaml
--- a/.github/workflows/CI-CD.yaml
+++ b/.github/workflows/CI-CD.yaml
@@ -109,19 +109,19 @@ jobs:
             pm2 save
       
       # Health check with retries
-      - name: Health check
-        run: |
-          echo "Waiting for the app to start..."
-          RETRIES=5
-          COUNT=0
-          until curl -s -f -X 'GET' 'http://ec2-98-83-207-140.compute-1.amazonaws.com:3000/health' -H 'accept: application/json'; do
-            if [ $COUNT -lt $RETRIES ]; then
-              COUNT=$((COUNT+1))
-              echo "Retry $COUNT of $RETRIES..."
-              sleep 10  # Wait for 10 seconds before retrying
-            else
-              echo "Health check failed after $RETRIES attempts."
-              exit 1
-            fi
-          done
-          echo "Health check passed."
+       #- name: Health check
+         #run: |
+           #echo "Waiting for the app to start..."
+           #RETRIES=5
+           #COUNT=0
+           #until curl -s -f -X 'GET' 'http://ec2-98-83-207-140.compute-1.amazonaws.com:3000/health' -H 'accept: application/json'; do
+             #if [ $COUNT -lt $RETRIES ]; then
+               #COUNT=$((COUNT+1))
+               #echo "Retry $COUNT of $RETRIES..."
+               #sleep 10  # Wait for 10 seconds before retrying
+             #else
+               #echo "Health check failed after $RETRIES attempts."
+               #exit 1
+             #fi
+           #done
+           #echo "Health check passed."
