Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -7,7 +7,7 @@ on:
       - dev
 
 jobs:
-  build:
+  deploy:
     runs-on: ubuntu-latest
 
     steps:
@@ -29,9 +29,9 @@ jobs:
       - name: Build the project
         run: npm run build
 
-      # Set the app name and env based on the branch
-      - name: Set app name and env based on branch
-        id: set_app_name_env
+      # Set the app name based on the branch
+      - name: Set app name based on branch
+        id: set_app_name
         run: |
           if [[ $GITHUB_REF == "refs/heads/main" ]]; then
             echo "APP_NAME=mehubarim-server" >> $GITHUB_ENV
@@ -39,17 +39,7 @@ jobs:
           elif [[ $GITHUB_REF == "refs/heads/dev" ]]; then
             echo "APP_NAME=mehubarim-server-dev" >> $GITHUB_ENV
             echo "NODE_ENV=development" >> $GITHUB_ENV
-          fi
-
-  deploy:
-    runs-on: ubuntu-latest
-    needs: build  # This ensures the deploy job runs only after the build job is successful
-
-    steps:
-      - name: List workspace files
-        run: |
-          echo "Listing files in the workspace directory:"
-          ls -la /github/workspace
+            fi
       # Stop the app using PM2 on the remote server
       - name: Stop app using PM2
         uses: appleboy/ssh-action@v0.1.5
@@ -61,7 +51,6 @@ jobs:
             pm2 stop ${{ env.APP_NAME }} || echo "App not running, skipping stop."
             pm2 delete ${{ env.APP_NAME }} || echo "App not found, skipping delete."
             pm2 save || echo "No PM2 process list to save."
-
       # Rsync the build files to the remote server
       - name: Rsync deployment
         uses: burnett01/rsync-deployments@5.1
@@ -82,21 +71,22 @@ jobs:
           key: ${{ secrets.EC2_PRIVATE_KEY }}
           script: |
             pm2 start npm --name "${{ env.APP_NAME }}" --cwd ${{ secrets.DEPLOY_DIR }}${{ env.APP_NAME }} -- run NODE_ENV=${{ env.NODE_ENV }} node dist/main
-
-      # Optional: Health check (uncomment if needed)
-      # - name: Health check
-      #   run: |
-      #     echo "Waiting for the app to start..."
-      #     RETRIES=5
-      #     COUNT=0
-      #     until curl -s -f -X 'GET' 'http://ec2-98-83-207-140.compute-1.amazonaws.com:3000/health' -H 'accept: application/json'; do
-      #       if [ $COUNT -lt $RETRIES ]; then
-      #         COUNT=$((COUNT+1))
-      #         echo "Retry $COUNT of $RETRIES..."
-      #         sleep 10  # Wait for 10 seconds before retrying
-      #       else
-      #         echo "Health check failed after $RETRIES attempts."
-      #         exit 1
-      #       fi
-      #     done
-      #     echo "Health check passed."
+            pm2 save
+      
+      # Health check with retries
+       #- name: Health check
+         #run: |
+           #echo "Waiting for the app to start..."
+           #RETRIES=5
+           #COUNT=0
+           #until curl -s -f -X 'GET' 'http://ec2-98-83-207-140.compute-1.amazonaws.com:3000/health' -H 'accept: application/json'; do
+             #if [ $COUNT -lt $RETRIES ]; then
+               #COUNT=$((COUNT+1))
+               #echo "Retry $COUNT of $RETRIES..."
+               #sleep 10  # Wait for 10 seconds before retrying
+             #else
+               #echo "Health check failed after $RETRIES attempts."
+               #exit 1
+             #fi
+           #done
+           #echo "Health check passed."
